const TableData = [
    {
    active: true,
    totalMembers:3,
    creator:'admin',
    icon:"http://www.icon.com",
    comparedPrice: 19.9,
    depth: "15cm",
    description: "Officia amet eiusmod eu sunt tempor voluptate laboris velit nisi amet enim proident et. Consequat laborum non eiusmod cillum eu exercitation. Qui adipisicing est fugiat eiusmod esse. Sint aliqua cupidatat pariatur mollit ad est proident reprehenderit. Eiusmod adipisicing laborum incididunt sit aliqua ullamco.",
    extraShippingFee: 3,
    featuredImageId: 1,
    handle: "a-walk-amongst-friends-canvas-print",
    height: "24cm",
    id: "1",
    images: [
        { id: 0, url: "assets/images/ecommerce/a-walk-amongst-friends.jpg", type: "image" },
        { id: 0, url: "assets/images/ecommerce/a-walk-amongst-friends.jpg", type: "image" },
        { id: 1, url: "assets/images/ecommerce/a-walk-amongst-friends.jpg", type: "image" },
        { id: 2, url: "assets/images/ecommerce/a-walk-amongst-friends.jpg", type: "image" },
        { id: 3, url: "assets/images/ecommerce/a-walk-amongst-friends.jpg", type: "image" },
        { id: 4, url: "assets/images/ecommerce/a-walk-amongst-friends.jpg", type: "image" },
        { id: 5, url: "assets/images/ecommerce/a-walk-amongst-friends.jpg", type: "image" },
        { id: 6, url: "assets/images/ecommerce/a-walk-amongst-friends.jpg", type: "image" },
        { id: 7, url: "assets/images/ecommerce/a-walk-amongst-friends.jpg", type: "image" },
        { id: 8, url: "assets/images/ecommerce/a-walk-amongst-friends.jpg", type: "image" }],
    name: "ITS Test Group 2 Updated",
    priceTaxExcl: 9.309,
    priceTaxIncl: 10.24,
    quantity: 3,
    sku: "A445BV",
    tags: ["canvas-print", "nature"],
    taxRate: 10,
    weight: "3kg",
    width: "22cm",
},
{
    active: true,
    totalMembers:3,
    creator:'by uzair',
    icon:"http://www.icon.com",
    comparedPrice: 19.9,
    depth: "15cm",
    description: "Officia amet eiusmod eu sunt tempor voluptate laboris velit nisi amet enim proident et. Consequat laborum non eiusmod cillum eu exercitation. Qui adipisicing est fugiat eiusmod esse. Sint aliqua cupidatat pariatur mollit ad est proident reprehenderit. Eiusmod adipisicing laborum incididunt sit aliqua ullamco.",
    extraShippingFee: 3,
    featuredImageId: 1,
    handle: "a-walk-amongst-friends-canvas-print",
    height: "24cm",
    id: "2",
    images: [
        { id: 0, url: "assets/images/ecommerce/a-walk-amongst-friends.jpg", type: "image" },
        { id: 0, url: "assets/images/ecommerce/a-walk-amongst-friends.jpg", type: "image" },
        { id: 1, url: "assets/images/ecommerce/a-walk-amongst-friends.jpg", type: "image" },
        { id: 2, url: "assets/images/ecommerce/a-walk-amongst-friends.jpg", type: "image" },
        { id: 3, url: "assets/images/ecommerce/a-walk-amongst-friends.jpg", type: "image" },
        { id: 4, url: "assets/images/ecommerce/a-walk-amongst-friends.jpg", type: "image" },
        { id: 5, url: "assets/images/ecommerce/a-walk-amongst-friends.jpg", type: "image" },
        { id: 6, url: "assets/images/ecommerce/a-walk-amongst-friends.jpg", type: "image" },
        { id: 7, url: "assets/images/ecommerce/a-walk-amongst-friends.jpg", type: "image" },
        { id: 8, url: "assets/images/ecommerce/a-walk-amongst-friends.jpg", type: "image" }],
    name: "just for checking rows",
    priceTaxExcl: 9.309,
    priceTaxIncl: 10.24,
    quantity: 3,
    sku: "A445BV",
    tags: ["canvas-print", "nature"],
    taxRate: 10,
    weight: "3kg",
    width: "22cm",
}
]
export default TableData