const Data = {
    entities: [
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair 25",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair 27",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "686 Roosevelt Avenue Oviedo, FL 32765",
            avatar: "assets/images/avatars/Henderson.jpg",
            company: "Howcom",
            email: "henderson@withinpixels.com",
            id: "5725a680ae1ae9a3c960d487",
            jobTitle: "Web Designer",
            lastName: "Cambias",
            name: "Uzair Its",
            nickname: "Blizzard",
            notes: "",
            phone: "+1-202-555-0151",
        },
        {
            address: "194 Washington Avenue Saint Petersburg, FL 33702",
            avatar: "assets/images/avatars/Helen.jpg",
            company: "Subhow",
            email: "helen@withinpixels.com",
            id: "5725a6806acf030f9341e925",
            jobTitle: "Content Developer",
            lastName: "Sheridan",
            name: "Sinan",
            nickname: "Magicbattler",
            notes: "",
            phone: "+1-202-555-0163",
        },
        {
            address: "194 Washington Avenue Saint Petersburg, FL 33702",
            avatar: "assets/images/avatars/Helen.jpg",
            company: "Subhow",
            email: "helen@withinpixels.com",
            id: "5725a6806acf030f9341e925",
            jobTitle: "Content Developer",
            lastName: "Sheridan",
            name: "Sinan Its",
            nickname: "Magicbattler",
            notes: "",
            phone: "+1-202-555-0163",
        },
        {
            address: "194 Washington Avenue Saint Petersburg, FL 33702",
            avatar: "assets/images/avatars/Helen.jpg",
            company: "Subhow",
            email: "helen@withinpixels.com",
            id: "5725a6806acf030f9341e925",
            jobTitle: "Content Developer",
            lastName: "Sheridan",
            name: "Muzamil",
            nickname: "Magicbattler",
            notes: "",
            phone: "+1-202-555-0163",
        }
        ,
        {
            address: "194 Washington Avenue Saint Petersburg, FL 33702",
            avatar: "assets/images/avatars/Helen.jpg",
            company: "Subhow",
            email: "helen@withinpixels.com",
            id: "5725a6806acf030f9341e925",
            jobTitle: "Content Developer",
            lastName: "Sheridan",
            name: "Arshad",
            nickname: "Magicbattler",
            notes: "",
            phone: "+1-202-555-0163",
        },
        {
            address: "194 Washington Avenue Saint Petersburg, FL 33702",
            avatar: "assets/images/avatars/Helen.jpg",
            company: "Subhow",
            email: "helen@withinpixels.com",
            id: "5725a6806acf030f9341e925",
            jobTitle: "Content Developer",
            lastName: "Sheridan",
            name: "Arshad ITS",
            nickname: "Magicbattler",
            notes: "",
            phone: "+1-202-555-0163",
        }
        ,
        {
            address: "194 Washington Avenue Saint Petersburg, FL 33702",
            avatar: "assets/images/avatars/Helen.jpg",
            company: "Subhow",
            email: "helen@withinpixels.com",
            id: "5725a6806acf030f9341e925",
            jobTitle: "Content Developer",
            lastName: "Sheridan",
            name: "Muzamil Its",
            nickname: "Magicbattler",
            notes: "",
            phone: "+1-202-555-0163",
        }
    ],
    searchText: "",
    user: {
        avatar: "assets/images/avatars/profile.jpg",
        frequentContacts: ['5725a6809fdd915739187ed5', "5725a68031fdbb1db2c1af47", "5725a680606588342058356d", "5725a680e7eb988a58ddf303"],
        groups: [
            { contactIds: ["5725a680bbcec3cc32a8488a", "5725a680e87cb319bd9bd673", "5725a6802d10e277a0f35775"], id: "5725a6802d10e277a0f35739", name: "Friends" },
            { contactIds: ["5725a680bbcec3cc32a8488a", "5725a680e87cb319bd9bd673", "5725a6802d10e277a0f35775"], id: "5725a6802d10e277a0f35739", name: "Clients" },
            { contactIds: ["5725a680bbcec3cc32a8488a", "5725a680e87cb319bd9bd673", "5725a6802d10e277a0f35775"], id: "5725a6802d10e277a0f35739", name: "Recent Workers" },

        ],
        id: "5725a6802d10e277a0f35724",
        name: "John Doe",
        starred: ["5725a680ae1ae9a3c960d487", "5725a6801146cce777df2a08", "5725a680bbcec3cc32a8488a"]
    }
}

export default Data